# Numpy

Este notepad contiene un resumen sobre numpy y algunas de sus funcionalidades mas utilizadas.

## Ventajas

Estas son algunas de las ventajas de Numpy frente a las listas regulares de python.

1. Los arrays de Numpy son mucho mas rapidos para insertar, borrar, actualizar y leer datos.
2. Los arrays de Numpy contienen una funcionalidad mas extensa que los arrays regulares de python.
3. Los arrays de Numpy vienen con un monton de metodos y soportes para aritmetica avanzada y algebra lineal.
4. Numpy te provee de capacidad avanzadas para el corte de matrices multidimensionales.

## Array Methods

In [2]:
import numpy as np

# Metodos para crear arrays en Numpy utilizando array()

numbs_list = [10,12,14,16,20]
numbs_array = np.array(numbs_list)

type(numbs_array)

numpy.ndarray

In [3]:
# Tambien se pueden crear arrays multidimensionales

row_1 = [10,12,13]
row_2 = [45,32,16]
row_3 = [45,32,16]

numbs_2d = np.array([row_1,row_2,row_3])
numbs_2d.shape

(3, 3)

In [4]:
"""
Otro de los metodos es el arrange(), te permite crear numpy arrays que contengan
un range de numeros enteros. el primer parametro se va a incluir en el resultado, pero el ultimo es omitido.
"""

numbs_arr = np.arange(5,11)
print("Array simple con arange")
print(numbs_arr)

"""
Tambien se puede agregar un parametro mas para declarar un STEP. donde se define la distancia
entre dos numeros consecutivos en el array
"""
numbs_arr = np.arange(5,12,2)
print("Array simple con arange y step")
print(numbs_arr)



Array simple con arange
[ 5  6  7  8  9 10]
Array simple con arange y step
[ 5  7  9 11]


In [5]:
# El metodo ones() te permite crear numpy arrays con todos unos.

ones_array = np.ones(6)
print("Numpy array con todos 1")
print(ones_array) 

"""
Si le pasamos una tupla con 2 numeros podemos identificar al primer elemento como
el numero de filas y el segundo como el numero de columnas
"""
print("Numpy array con todos 1 pero definido como multidimencional")
ones_array = np.ones((6,4))
print(ones_array)

# Tambien existe el metodo zeros() que tiene la misma funcionalidad pero completa con 0.
print("Ejemplo utilizando zeros()")
zeros_array = np.zeros((5,5))
print(zeros_array)

Numpy array con todos 1
[1. 1. 1. 1. 1. 1.]
Numpy array con todos 1 pero definido como multidimencional
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ejemplo utilizando zeros()
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
"""
El metodo eye() es utilizada para crear matrices de identidad en formato de un array de 2 dimensiones
contiene una diagonal con 1s y el resto completa con 0
"""
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# El metodo random.rand() se puede utilizar para crear un array con distribucion uniforme -> 0 a 1.

uniform_random = np.random.rand(4,5)
print("Array de numpy con distribucion uniforme")
print(uniform_random)

# Tambien se puede utilizar random.randn() con una n al final para crear una distribucion normal -> -1 a 1
print("Array de numpy con distribucion normal")
normal_random = np.random.randn(4,5)
print(normal_random)

"""
Y finalmente random.randint() permite crear un array de numpy con numeros aleatorios enteros entre un rango.
recibe 2 parametros, el primero identifica el numero mas bajo, y segundo identifica el numero mas alto
y el ultimo parametro identifica el numero de enteros random que se va a generar en el rango
"""
print("Array de numpy con numeros enteros random")
integer_random = np.random.randint(10,50,5)
print(integer_random)

Array de numpy con distribucion uniforme
[[0.0377672  0.99108479 0.73913618 0.14310867 0.86228689]
 [0.76097712 0.04228039 0.53518444 0.30195708 0.98787155]
 [0.98457563 0.0963101  0.0850665  0.17048948 0.69884317]
 [0.40679457 0.34941646 0.03157084 0.88477163 0.7971099 ]]
Array de numpy con distribucion normal
[[ 0.37495953  0.36673443  0.20905861 -0.00747245  0.16368034]
 [-0.70486671  2.24766786 -1.45619861  0.4477639  -0.47374934]
 [-2.27215697 -0.05972072 -0.4297929  -0.1031286  -1.11461482]
 [-0.87753942  0.2942564  -0.65113145  0.31530833  0.44046044]]
Array de numpy con numeros enteros random
[10 28 19 31 19]


## Reformacion de arrays

In [8]:
"""
Los arrays de numpy puede ser reformados utilizando la funcion reshape()
hay que tener en cuenta que la multiplicacion entre el numero de columnas y de filas tienen
que ser iguales para poder realizar el reshape, por ejemplo 4 X 6 = 24, 3 X 8 = 24.
"""
uniform_random = np.random.rand(4,6)
uniform_random = uniform_random.reshape(3,8)
print(uniform_random)

[[0.74595201 0.35522332 0.56758164 0.56939893 0.17797391 0.48720235
  0.04926893 0.93246117]
 [0.89248707 0.82631353 0.56869421 0.43231351 0.65062424 0.71864046
  0.40294918 0.59272302]
 [0.03471224 0.4090511  0.52712321 0.0730711  0.83482193 0.0854264
  0.30713236 0.64301102]]


## Indexado y recorte de arrays

In [9]:
"""
Los array de numpy pueden ser indexados y recortados, los arrays en numpy se indexan igual que las listas normales
indices en numpy comienzan desde 0
"""
s = np.arange(1,11)
print(s)
print(s[1])

""" 
Para realizar un recorte de un array se tiene que indicar el inicio y el final del recorte
el primer indice se incluye y el ultimo se excluye
"""
print(s[1:9])

# Si solo se especifica uno solo, retorna desde el primer elemento hasta el que se indico o viseversa

print(s[:5])
print(s[5:])

"""
El recorte de array o Slicing, tambien puede ser aplicado en un array de 2 dimensiones.
pero tiene que se aplicado en cada fila.
"""
row_1 = [10,12,13]
row_2 = [45,32,16]
row_3 = [45,32,16]

numbs_2d = np.array([row_1, row_2, row_3])
print(numbs_2d[:2,:])

print(numbs_2d[:,:2])

print(numbs_2d[1:,1:])

[ 1  2  3  4  5  6  7  8  9 10]
2
[2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[ 6  7  8  9 10]
[[10 12 13]
 [45 32 16]]
[[10 12]
 [45 32]
 [45 32]]
[[32 16]
 [32 16]]


## Operaciones aritmeticas

In [10]:
"""
NumPy trae incorporado una variedad de funciones para realizar de manera performante
operaciones aritmeticas
"""

# la funcion sqrt() nos permite encontrar la raiz cuadrada de todos los elementos de una lista.

nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print("Raiz cuadrada de los elementos de la lista:")
print(np_sqr)

# Tambien tenemos la funcion log() para buscar los logaritmos de una lista
np_log = np.log(nums)
print("Logaritmos de los elementos de la lista:")
print(np_log)

# Con la funcion exp() podemos obtener los exponentes de todos los elementos de la lista
np_exp = np.exp(nums)
print("Exponentes de los elementos de la lista:")
print(np_exp)

# Podemos buscar los senos y cosenos de cada item en una lista 
np_sine = np.sin(nums)
print("senos de los elementos de la lista:")
print(np_sine)

np_cos = np.cos(nums)
print("cosenos de los elementos de la lista:")
print(np_cos)

Raiz cuadrada de los elementos de la lista:
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Logaritmos de los elementos de la lista:
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Exponentes de los elementos de la lista:
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
senos de los elementos de la lista:
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
cosenos de los elementos de la lista:
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


## Operaciones de algebra linear con Numpy

La ciencia de datos utiliza extensivamente algebra lineal
por eso el soporte avanzado que brinda Numpy para hacer operaciones rapidas, eficientes
lo hace uno de los mas utilizados en el dia a dia.

In [11]:
"""
Para buscar el producto punto de una matriz se puede utilizar la funcion dot()
el numero de columnas de la primera matriz tiene que ser igual al numero de filas
de la segunda matriz 
"""

A = np.random.randn(4,5)

B = np.random.randn(5,4)

Z = np.dot(A, B)

print(Z)

[[-0.69111375 -0.20386423  0.45038485  1.02057505]
 [-2.34203505  1.91530687  0.51769653  0.65580555]
 [ 2.85491346  1.18781255  3.05148706 -1.32824032]
 [ 3.03460013 -1.12884711 -0.01730985 -1.77235149]]


In [12]:
# Tambien podemos multiplicar dos matrices, para hacerlo las dimensiones de las 2 matrices tienen que se iguales

row_1 = [10,12,13]
row_2 = [45,32,16]
row_3 = [45,32,16]

numbs_2d = np.array([row_1,row_2,row_3])
multiply = np.multiply(numbs_2d, numbs_2d)
print(multiply)


[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


In [13]:
# Podemos buscar la inversa de una matriz con la funcion linalg.inv()

row_1 = [1,2,3]
row_2 = [0,1,4]
row_3 = [5,6,0]

numbs_2d = np.array([row_1,row_2,row_3])
inverse = np.linalg.inv(numbs_2d)
print(inverse)


[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [16]:
# Buscando la determinante de una matris con la funcion linalg.det()

row_1 = [1,2,3]
row_2 = [4,5,6]
row_3 = [7,8,9]

numbs_2d = np.array([row_1,row_2,row_3])
determinant = np.linalg.det(numbs_2d)
print(determinant)

0.0


In [17]:
# La funcion trace() nos permite obtener el resultado de la suma de los elementos ubicados en diagonal de una matriz.

row_1 = [1,2,3]
row_2 = [4,5,6]
row_3 = [7,8,9]

numbs_2d = np.array([row_1,row_2,row_3])
trace = np.trace(numbs_2d)
print(trace)

15
